services:
  - type: web
    name: myhomepage
    runtime: python
    plan: free
    branch: main
    rootDir: .
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
